### ISSUE TITLE
Enable Bot to Approve Pull Requests via GitHub Actions

### ISSUE THREAD

**Issue by mi8bi** [mi8bi/NameTidy#16]
### 📝 Summary

Currently, PRs created via GitHub Actions or by bots (e.g. `gemini-code-assist[bot]`) cannot be merged automatically because at least one approving review is required, and bot reviews do not count.

To address this, we want to allow the bot to programmatically approve PRs by granting appropriate permissions to the workflow.

---

### ✅ Tasks

- [x] Update workflow file (e.g. `.github/workflows/test.yml`)
- [x] Add the following `permissions` to allow PR approvals by the bot:
  ```yaml
  permissions:
    contents: read
    pull-requests: write
```
